spring:
  datasource:
    url: jdbc:mysql://mysql:3306/gov_interop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

logging:
  level:
    org.texas.dposervice: INFO
    org.springframework.security: WARN